outbreak_sim <- function(R0,var.par,max.gens,max.N){
  
  # create vectors to store number of infected hosts
  num.inf <- numeric(length=max.gens+1)    # number currently infected in each generation
  cumul.inf <- numeric(length=max.gens+1)  # cumulative number infected
  # start both of these at 1
  num.inf[1] <- 1
  cumul.inf[1] <- 1
  
  # simulate
  for(gen in 1:max.gens){  # loop over infection generations
    
    # draw random number of secondary infections generated by each host in previous generation
    new.inf.list <- rnbinom(n=num.inf[gen],size=1/var.par,mu=R0)
    
    # add up the total number of new infections in the new generation and store this in num.inf
    new.inf.tot <- sum(new.inf.list)
    num.inf[gen+1] <- new.inf.tot
    cumul.inf[gen+1] <- cumul.inf[gen] + new.inf.tot
    #num.inf <- c(num.inf,new.inf.tot)
    #cumul.inf <- c(cumul.inf,cumul.inf[gen]+new.inf.tot)
    
    if(new.inf.tot==0){  # if there are no new infections in this generation, the outbreak has died out and we can stop simulating
      num.inf <- num.inf[1:(gen+1)] # truncate num.inf at the last simulated generation
      cumul.inf[(gen+2):(max.gens+1)] <- cumul.inf[gen+1]
      cumul.inf <- cumul.inf[1:(gen+1)] # truncate
      break
    }
    
    if(new.inf.tot > max.N){  # if we have reached the max number
      num.inf <- num.inf[1:(gen+1)]  # truncate num.inf at the last simulated generation
      cumul.inf <- cumul.inf[1:(gen+1)]
      break  # stop simulating
    }
    
  }
  
  outbreak <- list("num.inf" = num.inf, "cumul.inf" = cumul.inf, "num.gens" = length(num.inf))
  
  return(outbreak)
  
}