# R script for Tutorial 2, week 6, Biodiversity Under Pressure course
# written by: Helen Alexander, Oct. 2023 and updated Oct. 2024

# This script implements a stochastic simulation of an infectious disease outbreak 
# after a pathogen introduction (spillover) into a focal host population.
# EXERCISE 1: What is the (random) number of secondary infections generated by 
# one infected host? This uses the model of host heterogeneity from Lloyd-Smith
# et al. 2005.
# EXERCISE 2: How many hosts get infected in a transmission chain (over multiple
# infection generations)? Does the outbreak die out or grow?


###### EXERCISE 1 ######
# secondary infections per host

# input parameters - YOU CAN VARY THESE
R0 <- 1.5   # mean number of secondary infections per host
var.par <- 0   # parameter controlling variation amongst hosts
num.draws <- 1  # number of hosts to sample

# randomly draw the number of secondary infections per host 
# from a negative binomial distribution (see Lloyd-Smith et al. 2005)
infections <- rnbinom(n=num.draws,size=1/var.par,mu=R0)

# print the result if only one draw
if(num.draws==1){ print(infections) }

# if multiple draws:
if(num.draws > 1){
  # output some summary stats (min, max, mean)
  print(paste("min =",min(infections), sep=" ")); print(paste("max =",max(infections), sep=" ")); print(paste("mean =",mean(infections), sep=" "))
  # plot the distribution - you can adjust how you plot this
  #hist(infections,breaks=seq(from=-0.5,to=max(infections)+0.5,by=1),probability=T,xlab="number of secondary infections",ylab="proportion of cases")
  hist(infections)
}



###### EXERCISE 2 ######
# outbreak size

# load required function
source("outbreak_sim_function.R")

### (a) Simulate and plot one outbreak

# INPUTS - (YOU CAN VARY THESE)
# Main input parameters - defining distribution of secondary infections, as in Exercise 1
R0 <- 1.5   # mean number of secondary infections per host
var.par <- 0   # parameter controlling variation amongst hosts
# Additional input parameters - simulation settings
max.gens <- 20  # maximum number of infection generations to simulate
max.N <- 1000   # max number of infected hosts (in one generation) to simulate

# SIMULATE ONE OUTBREAK
# Call the simulation function:
outbreak <- outbreak_sim(R0,var.par,max.gens,max.N)
# returns a list containing three elements:
  # num.inf (vector): the number of newly infected hosts in each infection generation
  # cumul.inf (vector): the cumulative number of infected hosts in the outbreak, up to each generation
  # num.gens (scalar): the number of generations simulated, including the first with the initial infected host

# PLOTTING OPTIONS
# Note that there are multiple plotting options here. Run one option at a time to get the plot you want.
# Feel free to make your own plot versions instead!

# Newly infected hosts over time (infection generations)
# linear scale
plot(0:max.gens,0:max.gens,type="n",ylim=c(0,max(outbreak$num.inf)+1),xlab="infection generation",ylab="number of infected hosts")
lines(0:(outbreak$num.gens-1),outbreak$num.inf,type="s",lwd=4,col='red')
# log scale
plot(0:max.gens,0.01+0:max.gens,log="y",type="n",ylim=c(0.9,max(outbreak$num.inf)+1),xlab="infection generation",ylab="number of infected hosts")
lines(0:(outbreak$num.gens-1),outbreak$num.inf+0.01,type="s",lwd=4,col='red')

# Cumulative number of infected hosts over time (infection generations)
# linear scale
plot(0:max.gens,0:max.gens,type="n",ylim=c(0,max(outbreak$cumul.inf)+1),xlab="infection generation",ylab="cumulative number of infected hosts")
lines(0:(outbreak$num.gens-1),outbreak$cumul.inf,type="s",lwd=4,col='red')
# log scale
plot(0:max.gens,0.01+0:max.gens,log="y",type="n",ylim=c(0.9,max(outbreak$cumul.inf)+1),xlab="infection generation",ylab="cumulative number of infected hosts")
lines(0:(outbreak$num.gens-1),outbreak$cumul.inf+0.01,type="s",lwd=4,col='red')


### (b) Generate a set of simulated outbreaks with given parameters and calculate summary statistics

# INPUTS - (YOU CAN VARY THESE)
# Main input parameters - defining distribution of secondary infections, as in Exercise 1
R0 <- 1.5   # mean number of secondary infections per host
var.par <- 0   # parameter controlling variation amongst hosts
# Additional input parameters - simulation settings
max.gens <- 20  # maximum number of infection generations to simulate
max.N <- 1000   # max number of infected hosts (in one generation) to simulate

num.sims <- 100  # number of simulations to run at a given parameter set

# SIMULATE 

# Initialize variables to store outputs of interest from each simulation
num.gens <- numeric(length=num.sims)      # number of generations in each simulation (including the initial one)
num.inf.peak <- numeric(length=num.sims)  # maximum number of infected hosts in any single generation
num.inf.end <- numeric(length=num.sims)   # number of infected hosts in the final simulated generation
outbreak.size <- numeric(length=num.sims) # cumulative number of infected hosts by the end of the simulation

# simulate num.sims outbreaks
for(sim in 1:num.sims){  # loop over simulation runs
  
  # Simulate one outbreak: note this will get over-written every time the loop runs
  outbreak <- outbreak_sim(R0,var.par,max.gens,max.N)
  
  # store summary statistics about this simulation
  num.gens[sim] <- outbreak$num.gens
  num.inf.peak[sim] <- max(outbreak$num.inf)
  num.inf.end[sim] <- rev(outbreak$num.inf)[1] # takes the last entry in num.inf
  outbreak.size[sim] <- rev(outbreak$cumul.inf)[1] # takes the last entry in cumul.inf
  
}  # end loop over simulations

# ANALYSE SUMMARY STATS: 
# See the tutorial guidance for some suggested questions to investigate.
# Try finding your own ways to look at the stats.
# Or if you just want a short-cut to one possible coding solution, open the script "outbreak_stats.R".

# You can identify which simulations went extinct and which are still active at 
# the end of the simulation using the following (gives a vector of sim numbers in each category):
sims.extinct <- which(num.inf.end==0)
sims.active <- which(num.inf.end > 0)