library(ggplot2)


#############
##Model skeleton
#############

##set up parameter values
sP <- ...
Kp <- ...
lP <- ...
hp <- ...
sL <- ...
Kl <- ...
lL <- ...
hl <- ...
sH <- ...
Kh <- ...
lH <- ...
hh <- ...
fC <- ...
eC <- ...
mC <- ...
fM <- ...
eM <- ...
mM <- ...
mW <- ...
b <- ...
g <- ...
dC <- ...
dM <- ...



nsteps <- 200
pop.df.0 <- data.frame(time=1:nsteps,P=numeric(nsteps),L=numeric(nsteps),H=numeric(nsteps),C=numeric(nsteps),M=numeric(nsteps),W=numeric(nsteps))

pop.df.0 <- within(pop.df.0,{
  P[1] <- ...
  L[1] <- ...
  H[1] <- ...
  C[1] <- ...
  M[1] <- ...
  W[1] <- ...
})


for(t in 1:(nsteps-1)){
  pop.df.0 <- within(pop.df.0,{
    P[t+1] <- max(0,...) ##plants consumed by Caribou
    L[t+1] <- max(0,...) ##lichen consumed by Caribou
    H[t+1] <- max(0,...) ##plants consumed by Moose
    
    C[t+1] <- max(0,...)
    
    M[t+1] <- max(0,...)
    
    W[t] <- max(0,...)
  })
}


colors <- c("Plants"="brown","Lichen"="orange","Shrubs"="green","Caribou"="purple","Moose"="blue","Wolf"="red")
ggplot(data = pop.df.0)+
  geom_line(mapping=aes(x=time,y=P,color="Plants")) +
  geom_line(mapping=aes(x=time,y=L,color="Lichen")) +
  geom_line(mapping=aes(x=time,y=H,color="Shrubs")) +
  geom_line(mapping=aes(x=time,y=C,color="Caribou")) +
  geom_line(mapping=aes(x=time,y=M,color="Moose")) +
  geom_line(mapping=aes(x=time,y=W,color="Wolf")) +
  geom_hline(yintercept=0,color="darkgrey") +
  geom_vline(xintercept=0,color="darkgrey") +
  labs(x = "Time", y = "Densities", color="Legend")+
  scale_color_manual(values = colors)




















